apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: d99v3kct7-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d693cacad8.d74e.p3.openshiftapps.com/rhtap/rhtap-qe:21d8857d538f531382c3e7bf1a336faf2b1d8ec3@sha256:8e05a9f730faa3024a47e805c02986919109ffa24d9ea91c85d016150f6e8f9e
          name: container-image
